version : '3.9'

services :
  web-app:
    build: .
    container_name: web-app
    ports:
      - 9080:80
    volumes:
    # Sesuaikan Path Kiri
      - ./src:/var/www/html
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"   # optional
    volumes:
    #sesuaikan path kiri
      - ./mysql/data:/var/lib/mysql